config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  root to: 'pages#home'
  get "/.well-known/acme-challenge/:id" => "pages#lets_encrypt"

  # Public routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/signup', to: 'users#new', as: 'sign_up'
  match '/404', to: 'errors#not_found', via: :all
  resource :session, only: [:create, :destroy]
  resources :users, only: [:create]
  resources :password_resets, only: [:new, :create, :edit, :index, :update]

  # Private routes
  # React routes
  namespace :api, constraints: { format: "json" } do
    resource :user, only: [:show] do
      resources :pursuits, only: [:show] do
        resources :pomodori, only: [:create]
      end
    end
    namespace :v1 do
      resource :authentications, only: [:create]
    end
  end

  resource :admin, only: [:show] do
    resources :users, except: [:new, :create], controller: "admin/users"
  end

  resource :user, only: [:update, :edit, :show] do
    get :change_password
    resources :pursuits do
      resources :pomodori, only: [:new, :create, :show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :reset_token, :invitation_code

  has_secure_password
  has_many :pursuits

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :timezone, presence: true

  after_save :invalidate_invitation

  def full_name
    "#{first_name} #{last_name}"
  end

  def todays_productivity
    {
      time: pursuits.map { |pursuit| pursuit.ranged_pomodori("today")[:time] }.sum,
      pomodori: pursuits.map { |pursuit| pursuit.ranged_pomodori("today")[:count] }.sum
    }
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute :reset_digest, User.digest(reset_token)
    update_attribute :reset_sent_at, Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def valid_reset_token?(token)
    Digest::SHA2.hexdigest(token.to_s) == reset_digest
  end

  def now
    TZInfo::Timezone.get(timezone).now
  end

  private

  def invalidate_invitation
    return if self.invitation_code.nil?
    invitation = Invitation.find_by_code self.invitation_code
    invitation.update_attributes user_id: self.id, used: true
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA2.hexdigest(token.to_s)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "users"

  def index
    authorize! :manage, :all
    @section_heading = "All Users"
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_authentication, only: [:show, :edit, :update]
  before_action :fetch_user, only: [:show, :edit, :update]

  def new
    @user = User.new
    render layout: "guest"
  end

  def edit
    @section_heading = "Edit my Account"
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Account successfully updated.'
      redirect_to user_path
    else
      flash[:danger] = 'Sorry, there was a problem with your last request.'
      render :edit
    end
  end

  def create
    return invalid_invitation_code unless valid_invitation?
    @user = User.new(user_params)
    @user.save ? sign_user_in : refuse_signup
  end

  def show
  end

  def change_password
    @section_heading = "Change my Password"
  end

  private

  def valid_invitation? 
    @invitation = Invitation.find_by_code user_params[:invitation_code]
    if @invitation.nil? || @invitation.used?
      false
    else
      true
    end
  end

  def fetch_user
    @user = current_user
  end

  def invalid_invitation_code
    @user = User.new form_values
    flash[:danger] = "Invalid invitation code."
    render :new, layout: "guest"
  end

  def refuse_signup
    flash[:danger] = 'We\'re sorry, but there was a problem...'
    render :new
  end

  def form_values
    form_values = user_params
    form_values.delete(:password)
    form_values.delete(:password_confirmation)
    form_values
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :timezone, :first_name, :last_name, :invitation_code
    )
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def last_login_info(user)
    return if user.last_login.nil?
    difference = Time.now - user.last_login
    number_of_days = (difference / 1.day).round
    "#{user.last_login.strftime("%m/%d/%y")} (#{number_of_days} days ago)"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def region_lookup(timezone)
    ActiveSupport::TimeZone::MAPPING.invert[timezone]
  end

  def gravatar_image_url(size: 80)
    hash = Digest::MD5.hexdigest current_user.email.downcase
    "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  end

  def display_name
    if current_user.full_name == " "
      truncate current_user.email, length: 20
    else
      truncate current_user.full_name, length: 20
    end
  end

  def active?(action)
    comparison_string = "#{controller_name}-#{action_name}"
    if comparison_string == action
      "nav-link--active"
    end
  end
end

app/views/users/change_password.html.haml
.content-panel.col-md-4
  = form_for current_user do |f|
    .form-group
      = f.label :password, class: "form__label"
      = f.password_field :password, class:  "form__input"
    .form-group
      = f.label :password_confirmation, class: "form__label"
      = f.password_field :password_confirmation, class: "form__input"
    .form-group
      %label.form__label
      = f.submit 'Change Password', class: "btn btn-md btn-clear branding-controls__control"

app/views/users/edit.html.haml
.edit-my-account
  .content-panel.col-md-3.edit-my-account__user-profile.user-profile
    = image_tag gravatar_image_url(size: 120), class: "user-profile__gravatar"
    %h4= display_name
    %p= current_user.email
    
  .content-panel.col-md-4
    .form{ rel: 'edit' }
      = form_for @user do |f|
        %div.form__field
          = f.label :email, 'Email', class: "form__label"
          = f.text_field :email, placeholder: 'new@youremail.com', class: "form__input"
        %div.form__field
          = f.label :password, "Password", class: "form__label"
          = link_to "Change my Password", change_password_user_path, class: "btn btn-sm btn-clear branding-controls__control branding-controls__control--small"
        %div.form__field
          = f.label :first_name, 'First Name', class: "form__label"
          = f.text_field :first_name, placeholder: 'John', class: "form__input"
        %div.form__field
          = f.label :last_name, 'Last Name', class: "form__label"
          = f.text_field :last_name, placeholder: 'Doe', class: "form__input"
        %div.form__field
          = f.label :timezone, 'Region', class: "form__label"
          = f.select :timezone, ActiveSupport::TimeZone::MAPPING, {}, class: 'form__timezones-select'
        %div.form__field
          %label.form__label
          = f.submit 'Save', class: "btn btn-md btn-clear branding-controls__control"

app/views/users/new.html.haml
.login.branding.branding--signup
  = image_tag "landing/logo.png", alt: "Aristotle", class: "branding__logo branding__logo--login"
  .form{ rel: "signup" }
    = form_for @user do |f|
      %div
        = f.label :email, 'Email', class: "form__label"
        = f.text_field :email, placeholder: 'someone@somewhere.com', class: "form__input form__input--login"
      %div
        = f.label :first_name, 'First Name', class: "form__label"
        = f.text_field :first_name, placeholder: 'John', class: "form__input form__input--login"
      %div
        = f.label :last_name, 'Last Name', class: "form__label"
        = f.text_field :last_name, placeholder: 'Doe', class: "form__input form__input--login"
      %div
        = f.label :password, 'Password', class: "form__label"
        = f.password_field :password, placeholder: 'Don\'t make it "password"...', class: "form__input form__input--login"
      %div
        = f.label :password_confirmation, 'Password Confirmation', class: "form__label"
        = f.password_field :password_confirmation, placeholder: 'Seriously, not a good idea...', class: "form__input form__input--login"
      %div
        = f.label :timezone, 'Timezone', class: "form__label"
        = f.select :timezone, ActiveSupport::TimeZone::MAPPING, class: 'timezones', class: "form__input form__input--login"
      %div
        = label_tag "Invitation Code", nil, class: "form__label"
        = text_field_tag "user[invitation_code]", nil, placeholder: "Invitation Code", class: "form__input form__input--login"
      %div
        = f.submit 'Sign Up', class: "btn btn-lg btn-clear branding-controls__control branding-controls__control--login"

app/views/users/show.html.haml
.module{ rel: 'account-view', :'data-email' => @user.email }
  %h2 Account Information
  %ul
    %li.timezone Region/Time Zone: #{region_lookup(@user.timezone)}