config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  root to: 'pages#home'
  get "/.well-known/acme-challenge/:id" => "pages#lets_encrypt"

  # Public routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/signup', to: 'users#new', as: 'sign_up'
  match '/404', to: 'errors#not_found', via: :all
  resource :session, only: [:create, :destroy]
  resources :users, only: [:create]
  resources :password_resets, only: [:new, :create, :edit, :index, :update]

  # Private routes
  # React routes
  namespace :api, constraints: { format: "json" } do
    resource :user, only: [:show] do
      resources :pursuits, only: [:show] do
        resources :pomodori, only: [:create]
      end
    end
    namespace :v1 do
      resource :authentications, only: [:create]
    end
  end

  resource :admin, only: [:show] do
    resources :users, except: [:new, :create], controller: "admin/users"
  end

  resource :user, only: [:update, :edit, :show] do
    get :change_password
    resources :pursuits do
      resources :pomodori, only: [:new, :create, :show]
    end
  end
end

app/models/pursuit.rb
class Pursuit < ActiveRecord::Base
  attr_accessor :pomodoro_length_in_minutes, :pomodoro_length_in_seconds

  belongs_to :user
  has_many :pomodori, dependent: :destroy

  # Validations
  validates_presence_of :name, :user_id
  validates :default_pomodoro_length, numericality: { greater_than: 0 }

  # Inclusions
  include TimeConversions

  before_validation :convert_length_to_seconds!

  def pomodori_count
    pomodori.count
  end

  def ranged_pomodori(lower_bound=beginning_of_time, upper_bound=end_of_today)
    pomodori = self.pomodori.
      where("created_at > ? AND created_at < ?", start_of_day(lower_bound), end_of_day(upper_bound))
    { count: pomodori.count, time: pomodori.sum("elapsed_time") }
  end

  def contributed_on?(date)
    pomodori.
      where(
        "created_at >= ? AND created_at <= ?",
        date.in_time_zone(user.timezone).utc,
        date.in_time_zone(user.timezone).end_of_day.utc,
      ).any?
  end

  private

  def start_of_day(date_string)
    if date_string == "today"
      date = users_timezone.now.beginning_of_day
    elsif date_string == "overall"
      date = Time.new(2000)
    else
      date = Time.strptime(date_string, "%Y%m%d").beginning_of_day
    end
    users_timezone.local_to_utc(date)
  end

  def end_of_day(date_string)
    date = Time.strptime(date_string, "%Y%m%d").end_of_day
    users_timezone.local_to_utc(date)
  end

  def users_timezone
    TZInfo::Timezone.get(user.timezone)
  end

  def end_of_today
    users_timezone.now.strftime("%Y%m%d")
  end
end

app/controllers/pursuits_controller.rb
class PursuitsController < ApplicationController
  layout 'users'
  before_action :ensure_authentication
  before_action :fetch_pursuit, only: [:show, :edit, :update, :destroy]

  def index
    @pursuits = current_user.pursuits
    @range = params[:range].nil? ? "today" : params[:range]
    @inspirational_quote = InspirationalQuote.random
    @section_heading = "Your Pursuits"
  end

  def new
    @pursuit = current_user.pursuits.new
    @section_heading = "Create a new Pursuit"
  end

  def create
    @pursuit = current_user.pursuits.new(pursuit_params)
    @pursuit.save ? allow_pursuit : refuse_pursuit
  end

  def show
    @section_heading = @pursuit.name
    @calendar = Calendar.new Date.today
    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @pursuit.to_json }
    end
  end

  def edit
    @section_heading = "Edit: #{@pursuit.name}"
  end

  def update
    @pursuit.update_attributes(pursuit_params) ? allow_pursuit : refuse_pursuit
  end

  def destroy
    if @pursuit.destroy
      flash[:success] = 'Pursuit deleted.'
      redirect_to user_pursuits_path
    else
      flash[:danger] = "Sorry! We weren't able to delete your pursuit. Please try again."
      redirect_to user_pursuit_path(@pursuit.id)
    end
  end

  private
    def allow_pursuit
      flash[:success] = 'Pursuit successfully created! Now get crackin\'!'
      redirect_to user_pursuit_path @pursuit.id
    end

    def refuse_pursuit
      flash[:danger] = "We're sorry, something went wrong..."
      render :new
    end

    def pursuit_params
      params.require(:pursuit).permit(:name, :pomodoro_length_in_minutes, :pomodoro_length_in_seconds)
    end

    def fetch_pursuit
      @pursuit = Pursuit.find(params[:id])
    end
end

app/helpers/pursuits_helper.rb
module PursuitsHelper
  def convert_total_seconds_of(time)
    @time = time
    "#{calculate_hours}:#{calculate_minutes}:#{calculate_seconds}"
  end

  def minute_selections
    %w(1 5 10 15 20 25 30 45 60 90 120).map do |choice|
      [choice.to_s.rjust(2, "0"), choice]
    end
  end

  def second_selections
    0.step(60, 10).map do |choice|
      [choice.to_s.rjust(2, "0"), choice]
    end
  end

  def default_minutes
    (@pursuit.default_pomodoro_length / 60)
  end

  def default_seconds
    @pursuit.default_pomodoro_length - (@pursuit.default_pomodoro_length / 60) * 60
  end

  def context_link(context)
    if context == @range
      content_tag(:strong, context.capitalize)
    else
      link_to context.capitalize, "/user/pursuits?range=#{context}"
    end
  end

  def date_classes(day, week)
    classes = ["date"]
    if week.index(day) == 0
      classes << "first"
    end
    today = DateTime.now.in_time_zone(@pursuit.user.timezone).to_date
    if day === today
      classes << "today"
    end
    if @pursuit.contributed_on? day
      classes << "contributed"
    end
    unless @calendar.date.all_month.include? day
      classes << "nonmonth"
    end
    classes.join " "
  end

  def calendar_date_display(day)
    if @calendar.date.beginning_of_month == day
      "#{day.strftime "%b"} 1"
    else
      "#{day.strftime "%-d"}"
    end
  end

  private

  def hours
    @time / 60 / 60
  end

  def minutes
    @time / 60
  end

  def seconds
    @time % 60
  end

  def calculate_hours
    pad(hours)
  end

  def calculate_minutes
    pad(minutes - hours * 60)
  end

  def calculate_seconds
    pad(seconds)
  end

  def pad(time)
    time < 10 ? "0#{time}" : time
  end

end

app/views/pursuits/edit.html.haml
= form_for @pursuit, url: user_pursuit_path(@pursuit) do |f|
  .form-group
    = f.label :name, 'Name'
    = f.text_field :name
  .form-group
    = f.label :pomodoro_length_in_minutes, "Minutes"
    = f.select :pomodoro_length_in_minutes, options_for_select(minute_selections, default_minutes)
    = f.label :pomodoro_length_in_seconds, "Seconds"
    = f.select :pomodoro_length_in_seconds, options_for_select(second_selections, default_seconds)
  .form-group
    = f.submit 'Save'
    = link_to 'Delete Pursuit', user_pursuit_path(@pursuit.id), method: :delete, data: { confirm: 'Are you sure you want to delete this pursuit?' }

app/views/pursuits/index.html.haml
.content-panel.content-panel--first.col-md-4{ rel: "pursuits" }
  .pursuits-context{ rel: "pursuits-context" }
    = context_link "today"
    |
    = context_link "overall"
  %hr
  %table.table.pursuits-table
    %thead.table__head
      %tr
        %th Name
        %th Time #{@range.downcase}
        %th
    %tbody
      - @pursuits.each do |pursuit|
        %tr.pursuit{ :'data-pursuit-id' => pursuit.id, :'data-pursuit-name' => pursuit.name }
          %td= link_to pursuit.name, user_pursuit_path(pursuit.id)
          %td.time-and-count #{convert_total_seconds_of(pursuit.ranged_pomodori(@range)[:time])}
          %td.actions
            = link_to new_user_pursuit_pomodoro_path(pursuit.id), class: "btn btn-xs btn-clear branding-controls__control branding-controls__control--large" do
              %i.fa.fa-play
            = link_to edit_user_pursuit_path(pursuit.id), id: "edit-pursuit", class: "btn btn-xs btn-clear branding-controls__control branding-controls__control--large" do
              %i.fa.fa-pencil-square-o
            = link_to user_pursuit_path(pursuit.id), class: "btn btn-xs btn-clear branding-controls__control branding-controls__control--large", method: :delete, data: { confirm: 'Are you sure you want to delete this pursuit?' } do
              %i.fa.fa-trash
    - if @range == "today"
      %tfoot.summary
        %td
        %td.summary__time{ rel: "pomodori-time" }= convert_total_seconds_of(current_user.todays_productivity[:time])
        %td
  = link_to "Add", new_user_pursuit_path, class: "btn btn-lg btn-clear branding-controls__control branding-controls__control--large"

app/views/pursuits/new.html.haml
.module
  = form_for [current_user, @pursuit] do |f|
    .form-group
      = f.label :name, 'Name of Pursuit'
      = f.text_field :name, placeholder: 'Take over the world in time for dinner...'
    .form-group
      = f.label :pomodoro_length_in_minutes, "Minutes"
      = f.select :pomodoro_length_in_minutes, options_for_select(minute_selections)
      = f.label :pomodoro_length_in_seconds, "Seconds"
      = f.select :pomodoro_length_in_seconds, options_for_select(second_selections)
    .form-group
      = f.submit 'Create'

app/views/pursuits/show.html.haml
.content-panel.content-panel--first.calendar.col-md-4{ rel: "pursuit-show" }
  %h3.panel-name Contributions
  %h4.month-name= Date.today.strftime "%B"
  %ul.calendar-row.day-names
    %li Sun
    %li Mon
    %li Tues
    %li Wed
    %li Thurs
    %li Fri
    %li Sat
  - @calendar.dates.each do |week|
    %ul.calendar-row
      - week.each do |day|
        %li{ class: date_classes(day, week) }= calendar_date_display day
.content-panel.clock.col-md-4
  %h3.panel-name Your clock
  = link_to "Start", new_user_pursuit_pomodoro_path(@pursuit.id), class: "btn btn-xs btn-clear branding-controls__control branding-controls__control--small"