config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  root to: 'pages#home'
  get "/.well-known/acme-challenge/:id" => "pages#lets_encrypt"

  # Public routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/signup', to: 'users#new', as: 'sign_up'
  match '/404', to: 'errors#not_found', via: :all
  resource :session, only: [:create, :destroy]
  resources :users, only: [:create]
  resources :password_resets, only: [:new, :create, :edit, :index, :update]

  # Private routes
  # React routes
  namespace :api, constraints: { format: "json" } do
    resource :user, only: [:show] do
      resources :pursuits, only: [:show] do
        resources :pomodori, only: [:create]
      end
    end
    namespace :v1 do
      resource :authentications, only: [:create]
    end
  end

  resource :admin, only: [:show] do
    resources :users, except: [:new, :create], controller: "admin/users"
  end

  resource :user, only: [:update, :edit, :show] do
    get :change_password
    resources :pursuits do
      resources :pomodori, only: [:new, :create, :show]
    end
  end
end

app/views/layouts/guest.html.haml
!!!
%html
  %head
    %title Aristotle
    = stylesheet_link_tag "shared/application", media: 'all'
    = stylesheet_link_tag "guest/application", media: 'all'
    %link{ href: "https://fonts.googleapis.com/css?family=Oswald:400,300", rel: "stylesheet", type: "text/css" }
    %meta{ name: "viewport", content: "width=device-width", "initial-scale": 1, "maximum-scale": 1, "user-scalable": "no" }
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag :div, content_tag(:span, msg, class: "notification__text"), rel: "#{name}-flash", class: "notification notification--#{name}"
    = yield

app/views/layouts/sessions.html.haml
!!!
%html
  %head
    %link{ href: "http://fonts.googleapis.com/css?family=Oswald:400,300", rel: "stylesheet", type: "text/css" }
    = stylesheet_link_tag "sessions/application", media: "all"
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, rel: "#{name}-flash" 
    = yield

app/views/layouts/users.html.haml
!!!
%html
  %head
    - if display_timer?
      = react_component "TimerTitle"
    - else
      %title Aristotle
    = stylesheet_link_tag "users/application"
    = stylesheet_link_tag "shared/application"
    = javascript_include_tag "users/application"
    = javascript_include_tag "react/application"
    %link{ href: "https://fonts.googleapis.com/css?family=Open+Sans:400,700", rel: "stylesheet", type: "text/css" }
    %link{ href: "https://fonts.googleapis.com/css?family=Oswald:400,300", rel: "stylesheet", type: "text/css" }
    %link{ rel: "manifest", href: "/manifest.json" }
    %meta{ name: "viewport", content: "width=device-width", "initial-scale": 1, "maximum-scale": 1, "user-scalable": "no" }
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag :div, content_tag(:span, msg, class: "notification__text"), rel: "#{name}-flash", class: "notification notification--#{name}"
    %div.table-layout__row.table-row
      %nav.side-nav.col-md-1
        - if user_signed_in?
          %ul
            %li.nav-link.user-avatar
              = link_to edit_user_path, id: "edit-account" do
                = image_tag gravatar_image_url(size: 60), alt: "User's Gravatar", class: "user-avatar__image"
                %p.user-avatar__name= display_name
            %li.side-nav__pursuits.nav-link.nav-link--normal{ class: active?("pursuits-index") }
              = link_to "/user/pursuits?range=today" do
                %i.fa.fa-clock-o.nav-link__icon
                %p Pursuits
            - if current_user.admin?
              %li.side-nav__admins.nav-link.nav-link--normal
                = link_to admin_path do
                  %i.fa.fa-lock.nav-link__icon
                  %p Admins
            %li.side-nav__logout.nav-link.nav-link--normal
              = link_to session_path, method: :delete do
                %i.fa.fa-power-off.nav-link__icon
                %p Logout
      %div.non-nav.col-md-11
        .main-heading
          %h2.main-heading__text= @section_heading
        .main-content.container-fluid
          = yield